#!/bin/bash

set -o errexit
set -o nounset

TOS=${1:-""}
[ -n "${TOS}" ] || {
    echo "error, TOS is empty "
    exit 1
}

ALL_DEV=$( rdma link | awk '{print $2}' | awk -F'/' '{print $1}'  | tr '\n' ' ' )
ROOT_DIR=/sys/kernel/config/rdma_cm
[ -d "${ROOT_DIR}" ] || {
    echo "error, ${ROOT_DIR} not found, the pod must mount the host's /sys/kernel/config"
    exit 1
}

echo "ALL_DEV: $ALL_DEV "
for DEV in $ALL_DEV ; do
	if [ ! -d "${ROOT_DIR}/${DEV}" ] ; then
		mkdir ${ROOT_DIR}/${DEV} || { echo "error, failed to set $DEV " ; continue ; }  
	fi 
	DIR="${ROOT_DIR}/${DEV}/ports/1"
  # example : /sys/kernel/config/rdma_cm/mlx5_14/ports/1/default_roce_tos
	DST="${DIR}/default_roce_tos"

	echo ""
	echo "${DST} = $(cat ${DST}) " 
	echo ${TOS} > ${DST}
	echo "set tos $TOS to ${DST}"
done


mount -o remount,rw /sys
for DEV in $ALL_DEV ; do
	echo ""
  # example: /sys/class/infiniband/mlx5_34/tc/1/traffic_class
	DST=/sys/class/infiniband/${DEV}/tc/1/traffic_class
	echo ${TOS} > $DST
	echo "set ${TOS} to ${DST}"
done

