#!/bin/bash

# Copyright 2024 Authors of spidernet-io
# SPDX-License-Identifier: Apache-2.0

#set -x
#set -o pipefail
set -o errexit
set -o nounset

source /usr/sbin/rdmatools

REMOTE_IP=$( getOneRemoteEndpoint )
echo "collecting local information ..."
LOCAL_ETH_INFO=$( GetUpEthernetIP )
echo "collecting remote ${REMOTE_IP} information ..."
REMOTE_ETH_INFO=$( ssh ${REMOTE_IP} " source /usr/sbin/rdmatools && GetUpEthernetIP " )

TestIperf(){
    echo ""
    echo "***************************************************************************************************************"
    echo "******************** ${CMD_CLI} case: test iperf between local node and a remote node ${REMOTE_IP} ************************"
    echo "********************                  Notice ! iperf run up to 40G                    ************************"
    echo "***************************************************************************************************************"
    echo ""

    #   interface IP  Mask
    #   net1 172.81.1.143 16
    echo ""
    echo "local node 127.0.0.1 information:"
    echo "ifname ip mask"
    echo "${LOCAL_ETH_INFO}"
    echo ""
    echo "remote node ${REMOTE_IP} information:"
    echo "ifname ip mask"
    echo "${REMOTE_ETH_INFO}"

    OLD=$IFS
    IFS=$'\n'
    for ITEM in ${LOCAL_ETH_INFO} ;do
        IFS=$OLD

        LOCAL_INTERFACE=$( echo "${ITEM}" | awk '{print $1}' )
        LOCAL_IP=$( echo "${ITEM}" | awk '{print $2}' )
        LOCAL_MASK=$( echo "${ITEM}" | awk '{print $3}' )

        IFS=$'\n'
        for LINE in ${REMOTE_ETH_INFO} ;do
            IFS=$OLD

            REMOTE_INTERFACE=$( echo "${LINE}" | awk '{print $1}' )
            REMOTE_IP=$( echo "${LINE}" | awk '{print $2}' )
            REMOTE_MASK=$( echo "${LINE}" | awk '{print $3}' )

            {
                if [ "${REMOTE_MASK}"x == "${LOCAL_MASK}"x ] && [ -n "${LOCAL_MASK}" ]; then
                    if CheckIPv4SameSubnet "${LOCAL_IP}" "${REMOTE_IP}" "${LOCAL_MASK}" || ( ((LOCAL_MASK==32)) && ((REMOTE_MASK==32))  ) ; then
                        echo ""
                        echo "=========================================================================================================================================================="
                        echo "================   ${CMD_CLI} iperf case: 127.0.0.1 (${LOCAL_INTERFACE} ${LOCAL_IP}) vs remote ${REMOTE_IP} (${REMOTE_INTERFACE} ${REMOTE_IP})   ================="
                        echo "=========================================================================================================================================================="
                        ssh ${REMOTE_IP}  " PID=\`ps aux | grep ${CMD_CLI} | grep -v grep | awk '{print \$2}' \` && [ -n \"\${PID}\" ] && kill -9 \${PID}  " || true
                        (
                            OPTIONS="${CMD_OPTIONS} -s "
                            echo "server on remote ${REMOTE_IP}: ${CMD_CLI} ${OPTIONS}"
                            ssh ${REMOTE_IP}  " ${CMD_CLI} ${OPTIONS} "
                        )&
                        sleep 3
                        OPTIONS="${CMD_OPTIONS} -c ${REMOTE_IP}"
                        echo "clinet on local: ${CMD_CLI} ${OPTIONS}"
                        ${CMD_CLI} ${OPTIONS}
                        ssh ${REMOTE_IP}  " PID=\`ps aux | grep ${CMD_CLI} | grep -v grep | awk '{print \$2}' \` && [ -n \"\${PID}\" ] && kill -9 \${PID}  " || true
                    fi
                fi
            }
        done
    done

}

#-------------------------
CMD_CLI=${CMD_CLI:-"iperf3"}
CMD_OPTIONS=${CMD_OPTIONS:-""}
TestIperf
