#!/bin/bash

# Copyright 2024 Authors of spidernet-io
# SPDX-License-Identifier: Apache-2.0

#set -x
#set -o pipefail
set -o errexit
set -o nounset


source /usr/sbin/rdmatools
GPU_NUM=$( GetGPUAmount )
(( GPU_NUM > 0 )) || { echo "error, there is no GPU detected" ; exit 1 ; }
echo "there is ${GPU_NUM} GPU locally"

POD_IP_LIST=$( getAllEndpoints 2>/dev/null )
POD_NUM=$( echo "${POD_IP_LIST}" | wc -l )
HOST_LIST=$( echo -n "${POD_IP_LIST}" | tr '\n' ',' )
(( POD_NUM > 0 )) || { echo "error, failed to detect pods" ; exit 1 ; }
echo "HOST_LIST: ${HOST_LIST}"

OSU_DIR="/opt/hpcx/ompi/tests/osu-micro-benchmarks-cuda"
CMD_NAME=${CMD_NAME:-"osu_allreduce"}
CMD_PATH="${OSU_DIR}/${CMD_NAME}"
CMD_OPTIONS=${CMD_OPTIONS:-"-x 1000 -i 10000 -d cuda D D"}

echo ""
echo "***************************************************************************************************************"
echo "********************  osu: mpirun for ${CMD_NAME}                         ************************"
echo "********************              hcoll: disabled                                      ************************"
echo "***************************************************************************************************************"

HOST_SLOT=$( echo -n "${HOST_LIST}" | tr ',' "\n" | sed -E 's?(.*)?\1:'1'?g' | tr '\n' ',' )
PARAMETERS=" -np $(( POD_NUM )) -H ${HOST_SLOT}  \
   --bind-to none \
   -x PATH \
   -x LD_LIBRARY_PATH \
   -mca coll_hcoll_enable 0 \
   ${CMD_PATH}   ${CMD_OPTIONS}  "

# for log
echo "-------------------------------  run with enabling GDR and gdrCopy --------------------------"
OPTIONS=" -d  \
          -x UCX_LOG_LEVEL=INFO -x UCX_PROTO_ENABLE=y -x UCX_PROTO_INFO=y \
          -x HCOLL_LOG_LEVEL=INFO \
         -x UCX_IB_GPU_DIRECT_RDMA=yes \
         -x UCX_TLS=all \
         ${PARAMETERS}  "
echo ""
echo " mpirun ${OPTIONS} "
echo ""
mpirun ${OPTIONS}

# for result
echo ""
echo "------------------------------  run with disabling GDR  -----------------------------"
OPTIONS="\
         -x UCX_IB_GPU_DIRECT_RDMA=no \
         ${PARAMETERS}  "
echo ""
echo " mpirun ${OPTIONS} "
echo ""
mpirun ${OPTIONS}


echo ""
echo "-----------------------------   run with enabling GDR and gdrCopy -------------------------------"
OPTIONS="\
         -x UCX_IB_GPU_DIRECT_RDMA=yes \
         ${PARAMETERS}  "
echo ""
echo " mpirun ${OPTIONS} "
echo ""
mpirun ${OPTIONS}
