#!/bin/bash

# Copyright 2024 Authors of spidernet-io
# SPDX-License-Identifier: Apache-2.0

:<<EOF
在所有主机上的所有 rdma device 上分别启动一个 RDMA server, 
顺序的，本地通过同轨的 rdma device 并行访问远端的 RDMA server

example1:
    DURATION=30 LOOP_TIMES=2 ASYNCHRONOUS=true  testRdmaBroadcast 

example2:
    DURATION=5  LOOP_TIMES=1 ASYNCHRONOUS=false testRdmaBroadcast  "10.0.0.10  10.0.0.2"

rdma cm:
    DURATION=5  LOOP_TIMES=1 ASYNCHRONOUS=false ENABLE_RDMA_QOS=true RDMA_QOS=160 testRdmaBroadcast  "10.0.0.10  10.0.0.2"

exclude
    EXCLUDE_ENDPOINT="10.0.0.10 10.0.0.2" DURATION=10 LOOP_TIMES=1 ASYNCHRONOUS=false  testRdmaBroadcast 

EOF


#set -x
#set -o pipefail
set -o errexit
set -o nounset

if ! which ib_write_bw &>/dev/null; then
    echo "error, ib_write_bw tools not found"
    exit 1
fi

CURRENT_FILENAME=$(basename $0)
ENV_SSH_PORT=${ENV_SSH_PORT:-"2022"}

source /usr/sbin/rdmatools
source getAllEndpoints

POD_IP_LIST=${1:-""}
if [ -z "${POD_IP_LIST}" ] ;then 
    POD_IP_LIST=$(getOtherEndpoints 2>/dev/null) || true
fi

if [ -n "${EXCLUDE_ENDPOINT}" ]; then
    echo ""
    TMP_LIST=""
    for ADDR in ${POD_IP_LIST} ; do
        ! grep " ${ADDR} " <<< " ${EXCLUDE_ENDPOINT} " &>/dev/null || { echo "exclude ${ADDR}" && continue ; }
        TMP_LIST="${TMP_LIST} ${ADDR}"
    done
    POD_IP_LIST="${TMP_LIST}"
fi

echo ""
echo "POD_IP_LIST: ${POD_IP_LIST}"
echo ""
[ -n "${POD_IP_LIST}" ] || {
    echo "error, no remote hosts "
    exit 1
}

DEFAULT_LOCAL_INT=$( ip r | grep default | grep -Eo "dev .*" | awk '{print $2}' )
LOCAL_IP=$( ip -4 addr show ${DEFAULT_LOCAL_INT} | grep -oP '(?<=inet\s)[0-9]+(\.[0-9]+){3}' | head -1 )

WORKDIR="/tmp/${CURRENT_FILENAME}-$(date +%Y%m%d%H%M%S%N)"
REMOTE_INFOR_DIR="${WORKDIR}/remoteip"
REMOTE_OUTPUT_DIR="${WORKDIR}/output"
RESULT_DIR="${WORKDIR}/result"
mkdir -p ${WORKDIR}
mkdir -p ${REMOTE_INFOR_DIR}
mkdir -p ${RESULT_DIR}
mkdir -p ${REMOTE_OUTPUT_DIR}

echo "collecting local information ..."
LOCAL_RDMA_INFO=$(GetLocalRdmaDeviceIP)
[ -n "${LOCAL_RDMA_INFO}" ] || {
    echo "error, failed to get local rdma information"
    exit 1
}
LOCAL_INT=$( ip r | grep default | head -1 | grep -oE "dev [^[:space:]]+"  | awk '{print $2}' )
LOCAL_ENDPOINT_IP=$( ip -4 addr show ${LOCAL_INT} | grep -oP '(?<=inet\s)[0-9]+(\.[0-9]+){3}'	 )


echo "collecting remote information ..."
EXPECT_NUM=0
for ADDR in ${POD_IP_LIST}; do
    ((EXPECT_NUM += 1))
    (
        echo "collecting information from ${ADDR}"
        REMOTE_RDMA_INFO=$(ssh  -p ${ENV_SSH_PORT} ${ADDR} " source /usr/sbin/rdmatools && GetLocalRdmaDeviceIP ")
        if [ -n "${REMOTE_RDMA_INFO}" ]; then
            echo "${REMOTE_RDMA_INFO}" >${REMOTE_INFOR_DIR}/${ADDR}
        else
            echo "error, failed to get rdma information from remote ${ADDR}"
        fi
    ) &
done
wait
NUM=$(ls ${REMOTE_INFOR_DIR} | wc -l)
((NUM == EXPECT_NUM)) || {
    echo "error, failed to get information from all hosts"
    exit 1
}
echo "finished collectiong information"


RunLocalClient() {
    REMOTE_HOST="${1}"
    REMOTE_NODE_NAME=$( GetNodeName ${REMOTE_HOST} )

    [ -f "${REMOTE_INFOR_DIR}/${REMOTE_HOST}" ] || {
        echo "error, failed to find ${REMOTE_INFOR_DIR}/${REMOTE_HOST} "
        exit 1
    }
    RESULT_FILE="${RESULT_DIR}/${REMOTE_HOST}"

    echo "" >>${RESULT_FILE}
    printf "_____________________________________________________________________________________________________________________________________________________\n" >>${RESULT_FILE}
    printf "%-40s\t%-40s\t%-20s%-20s%-20s\n" "from ${LOCAL_ENDPOINT_IP} ${ENV_LOCAL_NODE_NAME}" "to ${REMOTE_HOST} ${REMOTE_NODE_NAME}" "BW avg[Gb/sec]" "MsgRate[Mpps]" "maxSpeed" >>${RESULT_FILE}
    printf "_____________________________________________________________________________________________________________________________________________________\n" >>${RESULT_FILE}

    REMOTE_RUN_OUTPUT_DIR="${REMOTE_OUTPUT_DIR}/${REMOTE_HOST}"
    mkdir -p ${REMOTE_RUN_OUTPUT_DIR}
    PORT=${START_PORT}
    COUNTER=0


    while read LINE; do
        REMOTE_DEVICE=$(echo "${LINE}" | awk '{print $1}')
        REMOTE_INTERFACE=$(echo "${LINE}" | awk '{print $2}')
        REMOTE_IP=$(echo "${LINE}" | awk '{print $3}')
        REMOTE_MASK=$(echo "${LINE}" | awk '{print $4}')
        REMOTE_PROTOCOL=$(echo "${LINE}" | awk '{print $5}')
        REMOTE_INDEX=$(echo "${LINE}" | awk '{print $6}')
        [ -n "${REMOTE_DEVICE}" ] || continue 

        OLD=$IFS
        IFS=$'\n'
        for ITEM in ${LOCAL_RDMA_INFO}; do
            IFS=$OLD
            LOCAL_DEVICE=$(echo "${ITEM}" | awk '{print $1}')
            LOCAL_INTERFACE=$(echo "${ITEM}" | awk '{print $2}')
            LOCAL_IP=$(echo "${ITEM}" | awk '{print $3}')
            LOCAL_MASK=$(echo "${ITEM}" | awk '{print $4}')
            LOCAL_PROTOCOL=$(echo "${ITEM}" | awk '{print $5}')
            LOCAL_INDEX=$(echo "${ITEM}" | awk '{print $6}')

            if [ "${REMOTE_MASK}"x == "${LOCAL_MASK}"x ] && [ -n "${LOCAL_MASK}" ]; then
                if CheckIPv4SameSubnet "${LOCAL_IP}" "${REMOTE_IP}" "${LOCAL_MASK}"; then

                    echo ""
                    echo "-------------------------------------------------------------------------------------------------"
                    echo "${CURRENT_FILENAME} case: local node ( ${LOCAL_INTERFACE} ${LOCAL_DEVICE} ${LOCAL_IP} ) and the remote node ${REMOTE_HOST} ( ${REMOTE_INTERFACE} ${REMOTE_DEVICE} ${REMOTE_IP} )  "

                    REMOTE_RUN_IP_OUTPUT_DIR="${REMOTE_RUN_OUTPUT_DIR}/${REMOTE_IP}"

                    MAX_SPEED=$(ethtool ${LOCAL_INTERFACE} | grep Speed | awk '{print $2}')
                    if ! ping -I ${LOCAL_INTERFACE} -c 2 ${REMOTE_IP} &>/dev/null; then
                        echo "error, failed to ping remote ${REMOTE_IP} from local interface ${LOCAL_INTERFACE}"
                        printf "%-40s\t%-40s\t%-20s%-20s%-20s\n" "${LOCAL_INTERFACE}/${LOCAL_DEVICE}/${LOCAL_IP}" "${REMOTE_INTERFACE}/${REMOTE_DEVICE}/${REMOTE_IP}" "failure" "failure" "${MAX_SPEED}" >>${RESULT_FILE}
                    else
                        OPTIONS="-d ${LOCAL_DEVICE} -x ${LOCAL_INDEX} -p ${PORT} ${CMD_OPTIONS} ${REMOTE_IP}"
                        echo "clinet on local: ${CMD_CLI} ${OPTIONS}"
                        if [ "${ASYNCHRONOUS}"x == "true"x ]; then
                        (
                            { ${CMD_CLI} ${OPTIONS} | tee ${REMOTE_RUN_IP_OUTPUT_DIR}; } || true
                            BANDWITDH=$(cat ${REMOTE_RUN_IP_OUTPUT_DIR} | grep -A 1 "BW average" | grep -E "[0-9\.]+" | awk '{print $4 }') || true
                            PPS=$(cat ${REMOTE_RUN_IP_OUTPUT_DIR} | grep -A 1 "BW average" | grep -E "[0-9\.]+" | awk '{print $5 }') || true
                            if [ -n "${BANDWITDH}" ]; then
                                printf "%-40s\t%-40s\t%-20s%-20s%-20s\n" "${LOCAL_INTERFACE}/${LOCAL_DEVICE}/${LOCAL_IP}" "${REMOTE_INTERFACE}/${REMOTE_DEVICE}/${REMOTE_IP}" "${BANDWITDH}" "${PPS}" "${MAX_SPEED}" >>${RESULT_FILE}
                            else
                                echo "error, failed to test remote ${REMOTE_HOST} ( ${REMOTE_INTERFACE} ${REMOTE_DEVICE} ${REMOTE_IP} ) "
                                printf "%-40s\t%-40s\t%-20s%-20s%-20s\n" "${LOCAL_INTERFACE}/${LOCAL_DEVICE}/${LOCAL_IP}" "${REMOTE_INTERFACE}/${REMOTE_DEVICE}/${REMOTE_IP}" "0" "0" "${MAX_SPEED}" >>${RESULT_FILE}
                            fi
                        )&
                        else
                            { ${CMD_CLI} ${OPTIONS} | tee ${REMOTE_RUN_IP_OUTPUT_DIR}; } || true
                            BANDWITDH=$(cat ${REMOTE_RUN_IP_OUTPUT_DIR} | grep -A 1 "BW average" | grep -E "[0-9\.]+" | awk '{print $4 }') || true
                            PPS=$(cat ${REMOTE_RUN_IP_OUTPUT_DIR} | grep -A 1 "BW average" | grep -E "[0-9\.]+" | awk '{print $5 }') || true
                            if [ -n "${BANDWITDH}" ]; then
                                printf "%-40s\t%-40s\t%-20s%-20s%-20s\n" "${LOCAL_INTERFACE}/${LOCAL_DEVICE}/${LOCAL_IP}" "${REMOTE_INTERFACE}/${REMOTE_DEVICE}/${REMOTE_IP}" "${BANDWITDH}" "${PPS}" "${MAX_SPEED}" >>${RESULT_FILE}
                            else
                                echo "error, failed to test remote ${REMOTE_HOST} ( ${REMOTE_INTERFACE} ${REMOTE_DEVICE} ${REMOTE_IP} ) "
                                printf "%-40s\t%-40s\t%-20s%-20s%-20s\n" "${LOCAL_INTERFACE}/${LOCAL_DEVICE}/${LOCAL_IP}" "${REMOTE_INTERFACE}/${REMOTE_DEVICE}/${REMOTE_IP}" "0" "0" "${MAX_SPEED}" >>${RESULT_FILE}
                            fi
                            ((COUNTER++))
                        fi
                    fi
                fi
            fi
        done

        (( PORT = PORT + 1))
    done <${REMOTE_INFOR_DIR}/${REMOTE_HOST}

    printf "_____________________________________________________________________________________________________________________________________________________\n" >>${RESULT_FILE}

    echo "" >>${RESULT_FILE}
    echo ""


    # wait
    sleep 5
    if [ "${ASYNCHRONOUS}"x == "true"x ]; then
        sleep ${DURATION}
    else
        sleep $(( DURATION * COUNTER ))
    fi

}

RunPerOnHost() {
    REMOTE_HOST="${1}"
    REMOTE_NODE_NAME=$( GetNodeName ${REMOTE_HOST} )

    [ -f "${REMOTE_INFOR_DIR}/${REMOTE_HOST}" ] || {
        echo "error, failed to find ${REMOTE_INFOR_DIR}/${REMOTE_HOST} "
        exit 1
    }
    PORT=${START_PORT}

    ssh  -p ${ENV_SSH_PORT} ${REMOTE_HOST} "killall -9 ${CMD_CLI}" || true
    while read LINE; do
        REMOTE_DEVICE=$(echo "${LINE}" | awk '{print $1}')
        REMOTE_INTERFACE=$(echo "${LINE}" | awk '{print $2}')
        REMOTE_IP=$(echo "${LINE}" | awk '{print $3}')
        REMOTE_MASK=$(echo "${LINE}" | awk '{print $4}')
        REMOTE_PROTOCOL=$(echo "${LINE}" | awk '{print $5}')
        REMOTE_INDEX=$(echo "${LINE}" | awk '{print $6}')

        [ -n "${REMOTE_DEVICE}" ] || continue 

        OPTIONS="-d ${REMOTE_DEVICE} -x ${REMOTE_INDEX} ${CMD_OPTIONS} "
        OPTIONS+=" -p ${PORT} "
        echo "server on remote ${REMOTE_HOST} for ${REMOTE_INTERFACE} with ${REMOTE_IP}: ${CMD_CLI} ${OPTIONS}"
        (
            #ssh  -p ${ENV_SSH_PORT} ${REMOTE_HOST} " PID=\`ps aux | grep ${CMD_CLI} | grep -v grep | awk '{print \$2}' \` && [ -n \"\${PID}\" ] && { echo \"\${PID}\" | xargs -n 1 -i  kill -9 {} ; } " || true
            ssh  -p ${ENV_SSH_PORT} ${REMOTE_HOST} "${CMD_CLI} ${OPTIONS} " &>/dev/null
        )&

        ((PORT=PORT+1))

    done <${REMOTE_INFOR_DIR}/${REMOTE_HOST}

}


TestRdma() {
    rm -rf ${RESULT_DIR}/*

    echo " run server on all rdma devices of remote nodes, and run local client to visit them on each rdma device asynchronously"

    echo "------------------ run server on all devices of each node ------------------"
    for ADDR in ${POD_IP_LIST} ; do
        RunPerOnHost "${ADDR}"
    done
    echo ""

    echo "------------------ run local client to visit all remotes ------------------"
    for ADDR in ${POD_IP_LIST}; do
        RunLocalClient "${ADDR}"
    done
    echo ""


    echo ""
    echo "------------------ ${CURRENT_FILENAME} summary -------------------------"
    echo ""
    FILE_LIST=$(ls ${RESULT_DIR})
    for FILE_NAME in ${FILE_LIST}; do
        cat ${RESULT_DIR}/${FILE_NAME}
        echo ""
    done

    sleep 5

}

#-------------------------
DURATION=${DURATION:-"10"}
LOOP_TIMES=${LOOP_TIMES:-"1"}
START_PORT=${START_PORT:-"10001"}
# run all RDMA client asynchronously for each rdma device and each node
ASYNCHRONOUS=${ASYNCHRONOUS:-"true"}


RDMA_QOS=${RDMA_QOS:-""}
BW_CMD_CLI=${BW_CMD_CLI:-"ib_write_bw"}
ENABLE_RDMA_QOS=${ENABLE_RDMA_QOS:-""}
BW_CMD_OPTIONS=${BW_CMD_OPTIONS:-"--disable_pcie_relaxed --duration ${DURATION} --report_gbits -F -q 4 "}
[ "${ENABLE_RDMA_QOS}" != "true" ] || BW_CMD_OPTIONS="${BW_CMD_OPTIONS} --rdma_cm"
[ -z "${RDMA_QOS}" ] || BW_CMD_OPTIONS="${BW_CMD_OPTIONS} --tos ${RDMA_QOS}"

CMD_CLI="${BW_CMD_CLI}"
CMD_OPTIONS="${BW_CMD_OPTIONS}"

echo "run ${LOOP_TIMES} times with duration ${DURATION} of ${LOOP_TIMES} round, asynchronously is ${ASYNCHRONOUS}"
for ((i=1;i<=${LOOP_TIMES};i++)); do
    echo "===================================== round ${i} ===================================="
    TestRdma
    echo ""
done

