#!/bin/bash

# Copyright 2025 Authors of spidernet-io
# SPDX-License-Identifier: Apache-2.0

#set -x
#set -o pipefail
set -o errexit
set -o nounset

# mccl test requires mx-smi tools, if mx-smi tools not exist, exit 1
if ! which mx-smi &>/dev/null; then
   echo "error, mx-smi tools not found"
   exit 1
fi

source /usr/sbin/rdmatools
GPU_NUM=$(GetMXGPUAmount)
((GPU_NUM > 0)) || {
   echo "error, there is no GPU detected"
   exit 1
}
echo "there is ${GPU_NUM} GPU locally"

POD_IP_LIST=$(getAllEndpoints 2>/dev/null)
POD_NUM=$(echo "${POD_IP_LIST}" | wc -l)
HOST_LIST=$(echo -n "${POD_IP_LIST}" | tr '\n' ',')
((POD_NUM > 0)) || {
   echo "error, failed to detect pods"
   exit 1
}
echo "HOST_LIST: ${HOST_LIST}"

DEFAULT_ROUTE_NIC=$(GetDefaultGatewayNic)
[ -z "$DEFAULT_ROUTE_NIC" ] && echo "error, no found the default route nic" && exit 1
echo "DEFAULT_ROUTE_NIC: ${DEFAULT_ROUTE_NIC}"

MACA_PATH=${MACA_PATH:-"/opt/maca"}
LD_LIBRARY_PATH=${MACA_PATH}/lib:${MACA_PATH}/ompi/lib
BENCH_NAME=${MACA_PATH}/samples/mccl_tests/perf/tests/all_reduce_perf
OPAL_PREFIX=/opt/maca/ompi/
# todo: for infiniband , test sharp: -x NCCL_COLLNET_ENABLE=1  -x NCCL_ALGO=CollNet

# format like:
# 10.233.74.100:8,10.233.124.200:8
HOST_SLOT=$(echo -n "${HOST_LIST}" | tr ',' "\n" | sed -E 's?(.*)?\1:'${GPU_NUM}'?g' | tr '\n' ',')
echo "HOST_SLOT: ${HOST_SLOT}"

# mccl test for multi node
# Total number of GPUs participating in the test
CARD_NUM=$((POD_NUM * GPU_NUM))
# the ib device name or the prefix of ib device(used in cases where the name of the ib device is inconsistent)
IB_PORT=mlx

# for log
echo "-------------------------------  running with local node --------------------------"
OPTIONS=" -b 1K -e 1024M -d bfloat16 -f 2 -g 1 -n 10 "
echo ""
echo " ${MACA_PATH}/ompi/bin/mpirun -n ${GPU_NUM} --allow-run-as-root -mca pml ^ucx ${BENCH_NAME} ${OPTIONS}"
echo ""
${MACA_PATH}/ompi/bin/mpirun -n ${GPU_NUM} --allow-run-as-root -mca pml ^ucx ${BENCH_NAME} ${OPTIONS}

OPTIONS="\
   --allow-run-as-root \
   -n ${CARD_NUM} \
   -mca pml ^ucx -mca btl_tcp_if_include \
   ${DEFAULT_ROUTE_NIC} -host ${HOST_SLOT} "

BNECH_OPTIONS="-b 1K -e 1024M -f 2"

ENV_VAR="\
   -x MCCL_IB_HCA=${IB_PORT} \
   -x MCCL_P2P_LEVEL=sys \
   -x MCCL_NET_GDR_LEVEL=SYS \
   -x MCCL_CROSS_NIC=1 \
   -x MCCL_NET_GDR_LEVEL=LOC \
   -x MCCL_DEBUG_SUBSYS=^ALLOC \
"

echo ""
echo "----------------------  running with multi node: GDR disabled ------------------------"
echo ""
echo " ${MACA_PATH}/ompi/bin/mpirun ${OPTIONS} ${ENV_VAR} "
echo ""
${MACA_PATH}/ompi/bin/mpirun ${OPTIONS} ${ENV_VAR} -x MCCL_NET_GDR_LEVEL=LOC ${BENCH_NAME} ${BNECH_OPTIONS}

echo ""
echo "----------------------  running with multi node: GDR enabled ------------------------"
echo ""
echo " ${MACA_PATH}/ompi/bin/mpirun ${OPTIONS} ${ENV_VAR} "
echo ""
${MACA_PATH}/ompi/bin/mpirun ${OPTIONS} ${ENV_VAR} ${BENCH_NAME} ${BNECH_OPTIONS}
